[package]
name = "rust_c"
version = "0.1.0"
authors = ["dai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonic-channel = { version = "0.4", features=["ingest", "search"] }
rocksdb = { version = "0.15.0" }